### ISSUE TITLE
Nomenclatura de Providers

### ISSUE THREAD

**Issue by JorgeCoke** [marcoscgdev/IonicGiphyApp#1]
El fichero "providers/home.ts" debería llamarse "providers/gifs.provider.ts" ya que a pesar de inyectarse en el componente Home, el provider en sí ofrece "Gifs", no ofrece "Homes". Además de eso, ese provider puede ser inyectado en otros componentes que hagan uso de gifs; no tiene porqué haber relación entre el componente y el provider

**Comment by marcoscgdev** [comment]
Tiene todo el sentido. Muchas gracias por el consejo!! :smile:
